@startuml task8_1_t1
[*]-->Активная
state Активная {
  [*]-->Обычная
  Обычная-->Премиум : [Статус Клиента = Премиум]
  Премиум-->Обычная : [Статус Клиента = Обычный]
}
Активная-->Заблокированная : [Попытка мошенничества]
Активная-->Просроченная : [Таймаут 3 года]
Активная-->Утерянная : [Карта утеряна]
Утерянная-->Активная : [Карта найдена]
Утерянная-->Заблокированная: [Таймаут 7 суток]
Заблокированная-->[*]
@enduml