@startuml and_xor
|Клиент|
start
:Ввод учетных данных;
|Система|
if(Клиент есть в системе и верно ввел учетные данные?) then(Да) 
:Успешная авторизация;
else (Нет)
:Уведомление Клиента об ошибке ввода учетных данных;
:Предложению Клиенту зарегистрироваться или оформить заказ без регистрации;
endif
|Клиент|
:Выбор товаров и добавление их в корзину;
:Выбор способа доставки;
|Система|
if(Товар в наличии?) then(Нет)
|Система|
fork
:Предложение удалить товар из заказа;
fork again
:Предложение альтернативного товара;
end fork
|Клиент|
:Решение по отсутствующим товарам;
else (Да)
endif
|Система|
fork
:Запрос платежных данных у Клиента;
|Клиент|
:Выбор способа оплаты и ввод платежных данных;
|Система|
:Проверка платежных данных;
:Попытка списания;
fork again
:Генерация счета-фактуры;
fork again
:Уведомление склада о необходимости сборки заказа;
|Сотрудник склада|
:Сборка Заказа;
end fork
if(Оплата прошла успешно?) then(Да)
|Система|
:Изменение статуса Заказа на "Собран";
:Уведомление Клиента о Подтверждении Заказа;
|Сотрудник склада|
:Отправка Заказа;
|Система|
:Изменение статуса Заказа на "Отправлен";
:Уведомление Клиента об отправке Заказа;
|Курьер|
:Доставка Заказа;
|Система|
:Изменение статуса Заказа на "Доставлен";
:Уведомление Клиента о доставке Заказа;
stop
else (Нет)
:Уведомление Клиента о проблемах с оплатой, предложение повторить попытку оплаты или изменить способ оплаты;
|Клиент|
if(Клиент хочет отменить заказ?) then(Нет)
:Решение проблем с оплатой;
stop
else (Да)
|Система|
:Отменяет заказ;
end
endif
@enduml